"""Change category id

Revision ID: 2beb40555565
Revises: 3c3ce97910f5
Create Date: 2021-03-12 20:46:41.214383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2beb40555565'
down_revision = '3c3ce97910f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    op.add_column('product', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    op.create_table('product_image',
    sa.Column('width', sa.INTEGER(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('mimetype', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('original IN (0, 1)'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'product_id')
    )
    # ### end Alembic commands ###
