"""Change category id

Revision ID: bf7d908c6e50
Revises: f7dbd35a4f42
Create Date: 2021-03-11 14:51:44.661708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7d908c6e50'
down_revision = 'f7dbd35a4f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity_sales', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'stock')
    op.drop_column('product', 'quantity_sales')
    # ### end Alembic commands ###
